- LICENSE
- README.md
Add `LICENSE` to declare that this plugin is licensed under Apache License v2.
@johnscancella I think our license should be APL2, because we copy basic implementation from Gradle. Is my understanding right?
> close #1: add license file

- gradle/wrapper/gradle-wrapper.properties
To fix "Could not determine java version from ‘9.0.1’", we need to upgrade gradle.
https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457
> upgrade gradle to the latest version

- CHANGELOG.md
- build.gradle
- src/main/java/com/github/spotbugs/SpotBugsTask.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java
Fixes https://github.com/spotbugs/spotbugs/issues/506. Behaviour and naming is similar to the FindBugs plugin (see https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/findbugs/FindBugsSpecBuilder.java#L168).
> Add option to control progress reporting

- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsExtension.java
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
As discussed in https://github.com/spotbugs/spotbugs-gradle-plugin/pull/6 adding the `showProgress` option to task mappings.
> Add task mapping for `showProgress` option

- RELEASE_PROCEDURE.md
- build.gradle
- gradle/checkstyle.gradle
- gradle/jacoco.gradle
Update several tools that is used in our build. These changes don't affect built artifacts, so we don't need record in changelog.
> Update build related parts

- .gitignore
- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
- src/test/java/com/github/spotbugs/Bar.groovy
- src/test/java/com/github/spotbugs/FooTest.groovy
- src/test/java/com/github/spotbugs/MultipleBuildOutputSourceDirsTest.java
* Modification to handle changes made in gradle 4.0
- See https://docs.gradle.org/4.0/release-notes.html
Location of classes in the build directory
> Handle multiple output source directories

- CHANGELOG.md
- build.gradle
After we merge this PR, we need to tag db9796621629fd6326f8618ddc4660e881a8b396 or its rebased commit as `1.6.2` then Travis CI will publish the built gradle plugin.
> Release 1.6.2

- README.md
The old badge links were deprecated and removed, see https://about.sonarcloud.io/news/2018/02/05/new-project-badges.html
> Update links to sonarcloud badges

- CHANGELOG.md
- build.gradle
3.1.6 provides [better Java11 supports](https://github.com/spotbugs/spotbugs/blob/3.1.6/CHANGELOG.md) and several bug fixes.
> upgrade SpotBugs to 3.1.6

- .travis.yml
To find potential problem in early phase, build with Gradle 4.10-RC2 and 4.11 nightly release.
> Build with 4.10-rc-2 and 4.11 nightly release

- .travis.yml
- build.gradle
- gradle/deploy.gradle
Related with #41: this PR introduces `deploy` phase to Travis build, to deploy SNAPSHOT version to [the sonatype snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs-gradle-plugin/).
> Deploy SNAPSHOT version to Sonatype Snapshot repo

- src/main/java/com/github/spotbugs/SpotBugsTask.java
In a commit for Gradle 5.0 the internal class `org.gradle.api.internal.ClosureBackedAction` 
has been moved to org.gradle.util.ClosureBackedAction` 
(see https://github.com/gradle/gradle/commit/b16479080a8864f91d15540d41bc09bdbe2c0af3#diff-bd993f7b907baefcd8fcf66327841ed4).
This commit replaces the usage of `ClosureBackedAction` with `org.gradle.util.ConfigureUtil.configureUsing()`
which is available for a long time.
This fixes an exception when the plugin is used nightly builds of Gradle 5.0:
`java.lang.NoClassDefFoundError: org/gradle/api/internal/ClosureBackedAction`
> Replace usage of internal class ClosureBackedAction

- CHANGELOG.md
- build.gradle
This release uses [SpotBugs 3.1.7](https://github.com/spotbugs/spotbugs/blob/3.1.7/CHANGELOG.md) by default, for better Java 11 support.
It also supports Gradle v5.0 nightly release, that replaces usage of internal API. refs #52
> Release 1.6.4

- .travis.yml
Replaces snapshot/nightly Gradle build with a more stable milestone release.
> Test with Gradle 5.0-milestone-1

- build.gradle
Fixes #63 
This helps reduce the size of the buildscript classpath of consuming projects.
> Narrow the scope of spotbugs dependency

- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
- src/main/java/com/github/spotbugs/SpotBugsTask.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpec.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java
- src/test/java/com/github/spotbugs/SourceAnalysisProperty.java
- src/test/java/com/github/spotbugs/SourceAnalysisPropertyTest.java
SpotBugs’ source analysis requires a handle to the top-level source set
folder, or else the SourceFileFinder cannot locate attached sources
of a task. This is especially annoying when some checks require insight
into the source code (e.g. the SwitchFallthrough check, which looks
at comments inside a switch statement). Since SpotBugs tasks are essentially
Gradle SourceTasks, they use a FileTree internally, which only keeps
handles to the leaf files automatically, and doesn’t hold onto the original
directory:
```groovy
new File("src/main/java/com/example/MyFile.java").withWriter {
it.write("package com.example;\nclass MyFile {}"
}
def fileTree = project.fileTree("src/main/java")
for (file in fileTree.files) {
// This will not print "/.../src/main/java", but …
```
> Keep track of top-level source set folders

- CHANGELOG.md
- build.gradle
To solve #81, it is [necessary to deploy newer version](https://discuss.gradle.org/t/plugin-cannot-be-published-due-to-exists-already-error/29911/2) so this PR is going to release new version 1.6.8.
It also bump up SpotBugs version to the latest one.
> Release 1.6.8

- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
- src/test/java/com/github/spotbugs/Issue54Test.java
In the closure for `classes`, previously `it` returns each class file, however now it just return the root dir (classesDirs). a2740fff2c58d05c7720f7e819daf0ca827b95cd introduced this problem #54.
By this fix, we can resume using closure based filtering.
> Fix classes filtering

- src/test/java/com/github/spotbugs/Issue423Test.java
- src/test/java/com/github/spotbugs/Issue440Test.java
- src/test/java/com/github/spotbugs/Issue54Test.java
- src/test/java/com/github/spotbugs/KotlinBuildScriptTest.java
- src/test/java/com/github/spotbugs/MultipleBuildOutputSourceDirsTest.java
- src/test/java/com/github/spotbugs/MultipleClassDirsTest.java
- src/test/java/com/github/spotbugs/SourceAnalysisPropertyTest.java
- src/test/java/com/github/spotbugs/SpotBugsPluginTest.java
- src/test/resources/Issue423.gradle
- src/test/resources/Issue440.gradle
- src/test/resources/Issue54.gradle
- src/test/resources/KotlinBuildScript.gradle.kts
- src/test/resources/MultipleBuildOutputSourceDirsGroovy.gradle
- src/test/resources/MultipleBuildOutputSourceDirsScala.gradle
- src/test/resources/MultipleClassDirs.gradle
- src/test/resources/SourceAnalysisProperty.gradle
- src/test/resources/SpotBugsPlugin.gradle
Extract Gradle file into separated resource file. I wish [Raw String Literal](https://openjdk.java.net/jeps/326) will come to Java later...
I also deleted needless usage of local maven repository. I also removed the code that fixes spotbugs Gradle plugin version to `1.6.1`.
> Extract gradle file for test

- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsTask.java
allSource input creates different cache keys for same project checked out at different locations. This PR will fix it.
> Make task cacheable across checkouts

- CHANGELOG.md
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java
- src/test/java/com/github/spotbugs/Issue31Test.java
- src/test/resources/Issue31.gradle
There is no ["-text" option](https://spotbugs.readthedocs.io/en/stable/running.html) in SpotBugs option. Just skip adding "-text" option when text report is activated via Gradle plugin. This PR will fix #31.
> Fix #31 around text type bug report

- .travis.yml
- build.gradle
- gradle/sonar.gradle
Current `gradle/sonar.gradle` uses removed feature: branch analysis and old pre-merge analysis. So the build in other PR is failed.
Both can be replaced by the official SonarCloud add-on, suggested by this PR.
> Fix sonarcloud related build

- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
This PR fixes #47. I think it needs no CHANGELOG entry because it doesn't affect any output from this plugin.
> Remove no-op stream code

- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsTask.java
- src/main/java/com/github/spotbugs/internal/SpotBugsHtmlReportImpl.java
- src/main/java/com/github/spotbugs/internal/SpotBugsReportsImpl.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java
- src/test/java/com/github/spotbugs/HtmlReportTest.java
- src/test/resources/HtmlReportTest.gradle
Support `-projectName` and `-release` option that makes reporting better. By default, it uses project name and version.
Also add `setStylesheet(String)` for HTML report: For now we only has `setStylesheet(TextResource)` but XSL is packaged into `spotbugs.jar` then it is good to support the path for zip entries.
This PR closes #111. Also close #107.
> feat: Improvements for HTML reporting

- .travis.yml
The secure variable is not used in the PR comes from forks.
So before we trigger SonarQube analysis, make sure the `$SONAR_LOGIN` variable exists or not.
This fix will solve the build failure in #137.
> ci: skip sonarqube analysis when PR comes from forks

- CHANGELOG.md
- build.gradle
Gradle 6 will remove deprecated API, then this release will be required for Gradle 6 users.
Note that Gradle 6 hasn't been released yet, but the last release for Gradle 5 (5.5) is coming.
This version works with Gradle 5.1+.
> Release v2.0.0 for Gradle 6 support

- build.gradle
- gradle/deploy.gradle
- src/main/java/com/github/spotbugs/SpotBugsTask.java
Hi!
Few things for Gradle 6 support:
* Upgrade `com.diffplug.gradle.spotless` to `3.24.2`
* Older versions fail in Gradle 6.x with the following: 
> Execution failed for task ':spotlessJava'. You must declare outputs or use `TaskOutputs.upToDateWhen()` when using the incremental task API
* Remove `@Optional` from `showProgress` in `SpotBugsTask`.
* Reason:  @Input properties with primitive type 'boolean' cannot be @Optional.
* Replace `compile` and `testCompile` with `implementation` and `testImplementation` as the former will be removed in Gradle 7.0 and now they trigger warnings on builds
> Update plugin to build with Gradle 6.x

- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
- src/main/java/com/github/spotbugs/SpotBugsTask.java
- src/test/java/com/github/spotbugs/Issue423Test.java
Current way create task instances even though it is not necessary.
This PR applies the same way with [the official CodeNarc plugin validating configuration in setter method](https://github.com/gradle/gradle/blob/df7ac484a2facbb4503ba911666367de22b1d16a/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcExtension.java).
This PR also changes the type of Exception from `IllegalStateException` to `IllegalUserDataException` that is recommended to make problem clear. This is also the same way with the plugin in above.
@daanschipper can I ask you to confirm this fix?
> Validate when plugin is configured

- .travis.yml
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
- src/main/java/com/github/spotbugs/internal/SpotBugsHtmlReportImpl.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsXmlReportImpl.java
- src/test/java/com/github/spotbugs/SpotBugsPluginTest.java
Hi!
With Gradle 6.1 around the corner, this is a potential issue: https://github.com/gradle/gradle/issues/11189
```
/home/travis/build/spotbugs/spotbugs-gradle-plugin/src/main/java/com/github/spotbugs/internal/SpotBugsHtmlReportImpl.java:17: error: SpotBugsHtmlReportImpl is not abstract and does not override abstract method getOutputLocation() in SimpleReport
public class SpotBugsHtmlReportImpl extends CustomizableHtmlReportImpl {
^
/home/travis/build/spotbugs/spotbugs-gradle-plugin/src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsXmlReportImpl.java:8: error: SpotBugsXmlReportImpl is not abstract and does not override abstract method getOutputLocation() in SimpleReport
public class SpotBugsXmlReportImpl extends TaskGeneratedSingleFileReport implements SpotBugsXmlReport {
^
2 …
```
> Gradle 6.1 support: make Html and Xml report implementation abstract so Gradle decorates the

- CHANGELOG.md
- build.gradle
To support Gradle 6.1, we need to drop support for 5.1.
To release this breaking change, I will bump up the major version to 3.
> Release 3.0.0

- CHANGELOG.md
- src/main/java/com/github/spotbugs/internal/SpotBugsHtmlReportImpl.java
I think `@Nested` is the correct annotation but my experience with writing gradle plugins is limited so feel free to correct me.
> Fixes deprecation warning when using Gradle 6. Resolves #171

- src/main/java/com/github/spotbugs/SpotBugsTask.java
When using Gradle Enterprise, builds failing due to Spotbugs violations were incorrectly classified as non-verification failures.
To classify failing builds due to Spotbugs violations, the exception message
should be prefixed. For more information see https://docs.gradle.com/enterprise/failure-classification/
The message can be prefixed with any of the following phrases, let me know if you would like a different one!
* Analysis failed
* Check failed
* Compilation failed
* Code generation failed
* Generation failed
* Lint failed
* Processing failed
* Test failed
* Tests failed
* Testing failed
* Verification failed
> Force classification of a build failure as a verification failure

- .idea/compiler.xml
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java
> Fix the issue 196

- src/functionalTest/groovy/com/github/spotbugs/snom/Issue196.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
This fix makes SpotBugs plugin makes the dependency onto `check` task when `java-base` plugin is applied. This change close #196 in the version `4.0.1` which expects that `java-base` plugin is already applied to the project.
> Try to reproduce the reported case, and fix it

- README.md
Currently the first view of our document has no link to the plugin portal, that helps user to start using our plugin.
We have link in the 'usage' part, but it could be too far for who gets used to Gradle plugin.
> Add a badge to link to the Plugin Portal

- build.gradle
More info https://blog.gradle.org/plugin-portal-update
> fix: mandatory update for plugin portal publishing

- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java
Using `getTasks().register()` avoids creating the tasks during configuration time.
Currently the plugin is creating  number of modules * number of sourcesets amount of tasks, slowing down the configuration time.
How can I build the plugin to test it locally to confirm that this solves the issue?
> fix: Use task creation avoidance api

- README.md
- build.gradle
SpotBugs 4.0.2 is out, so bump up the default `toolVersion` to it.
https://github.com/spotbugs/spotbugs/releases/tag/4.0.2
> Bump up the default toolVersion to 4.0.2

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
Hi folks, this is for https://github.com/spotbugs/spotbugs-gradle-plugin/issues/245 
"Spotbugs report path should be provided in output when process fails"
Currently when running spotbugs and getting a failure, you can see the following:
```
3:38:34 * What went wrong:
03:38:34 Execution failed for task ':server:spotbugsMain'.
03:38:34 > A failure occurred while executing com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor
03:38:34    > Verification failed: SpotBugs execution thrown exception
03:38:34 
``` 
In order to get more details, `--stacktrace` has to be enabled and also you don't get details on where the report was added, if it was XML or HTML or something else.
I think it would be nice if the plugin outputs the full path when the execution fails
> feat: show spotbugs report full path when spotbugs execution fails

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
Hi @KengoTODA 
This is to address https://github.com/spotbugs/spotbugs-gradle-plugin/issues/239
Found that having projects with massive classpaths can not be used with spotbugs plugin. For example:
```
17:29:09 Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/zulu-8-amd64/bin/java'' could not be started because the command line exceed operating system limits.
17:29:09 	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
17:29:09 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
17:29:09 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:372)
17:29:09 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
17:29:09 	at …
```
> feat: add support for auxclasspathFromFile in java process

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
> fix: SpotBugsTask was not cacheable

- src/functionalTest/groovy/com/github/spotbugs/snom/BasePluginFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
When user uses the `base` plugin, it's possible to have no reporting so `findReportPath()` returns `null`. This PR will fix this behavior, by simply skipping the report path.
> Stop printing null if no report is available

- .github/workflows/gradle.yml
- .gitignore
- README.md
- build.gradle
This pull request closes #192 - plugin not signed. Note that some additional work needs to be done by the maintainer, mainly generating the PGP keys, uploading them to the pool servers, and adding the secrets to the github repository. See README for instructions.
> sign gradle plugin

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
and auxclasspath file is removed and created instead of truncated in place
This addresses #259 by avoiding re-creating the same file in any invocation, and adds some additional information if a failure occurs.
> fix: create auxclasspath file for each spotbugs task

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
fixes #273 because some of the paths were using `/` while windows uses `\` for the path separator. Now use File.separator which will automatically choose the correct one based on which OS you are using.
> using File.separator so that paths are OS independent

- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
this fixes #284 - when suppressing stack trace still print message about where report is and what caused the error.
> always print message about failure and report location

- README.md
- build.gradle
This change will release the next patch version 4.4.2, to bump up the default `toolVersion` to [the latest spotbugs 4.0.5](https://github.com/spotbugs/spotbugs/releases/tag/4.0.5).
> Bump up the default toolVersion to 4.0.5

- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
* warning messages are now consistent with those reported by other native Gradle static code analysis tools (PMD, Checkstyle, etc...).
* fixes https://github.com/spotbugs/spotbugs-gradle-plugin/issues/286
> fix: Print report location as file uri and improve warning messages

- README.md
- build.gradle
4.0.5 has a critical issue around BCEL usage, so bump up the default `toolVersion` to the fixed version.
> fix: bump up the default toolVersion to 4.0.6

- .github/dependabot.yml
refs https://github.com/spotbugs/spotbugs/pull/1188
It seems that v2 provides better support to Gradle.
> Bump up dependabot to v2

- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
Declaring `auxClassPaths` as a `Classpath` property allows Gradle to perform additional normalization,
so that functionally-identical jar files do not trigger a re-execution of the SpotBugsTask. 
A re-generated jar containing identical classes will have different entry timestamps for each class entry,
and as such is not bitwise identical even though it is functionally identical.
Without this fix, changing an input jar file will change the input cache key, leading to consistent misses from the local build cache. 
See https://docs.gradle.org/6.0/userguide/more_about_tasks.html#sec:task_input_using_classpath_annotations
Note that I have tested this change locally, but not added any specific test coverage for this use case.
> fix: Use `Classpath` normalization for `auxClassPaths`

- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
we don't support Gradle < 3.2, so the InputFiles annotation is needless 
for fields which is already annotated with the Classpath annotation.
refs https://github.com/spotbugs/spotbugs-gradle-plugin/pull/314#issuecomment-700773441
> fix: remove needless annotation

- build.gradle
- gradle/HEADER.txt
- gradle/functional-test.gradle
- gradle/test.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/functionalTest/groovy/com/github/spotbugs/snom/AndroidFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/BasePluginFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/Issue196.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/Confidence.groovy
- src/main/groovy/com/github/spotbugs/snom/Effort.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsReport.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsSarifReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTextReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsXmlReport.java
- src/test/java/com/github/spotbugs/snom/SpotBugsPluginTest.java
Optimize Gradle build script for performance.
I also found that Groovydoc reports error because it fails parsing lambda in `.java` files.
We can solve it by migrating `.java` to `.groovy`, I will handle it in another PR.
> Build optimization

- .github/workflows/gradle.yml
- .github/workflows/javadoc.yml
Fix GitHub Actions that was broken by https://github.blog/changelog/2021-01-21-github-actions-short-sha-deprecation/
> Replace short SHA with tag name

- README.md
- build.gradle
This PR updates the default SpotBugs version to 4.2.1.
close #356
> Bump up the default SpotBugs version to 4.2.1

- package-lock.json
An old version of `yargs-parser` is used, and it has [a vulnerability `GHSA-p9pc-299p-vxgp`](https://github.com/advisories/GHSA-p9pc-299p-vxgp). To fix this problem, update the `conventional-commit-parser` which is used transitively.
```sh
npm install -D conventional-commits-parser
npm dedupe
npm uninstall conventional-commits-parser
```
I found these commands at [this blog post](https://dev.to/malykhinvi/fix-a-transitive-npm-dependency-vulnerability-4775) and confirmed that it surely removes `yargs-parser` version 10 from `package-lock.json`. Now we depend on suggested versions only: 13.1.2, 15.0.1, 18.1.1 or later.
> chore: Update yargs-parser

- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForHybrid.java
To fix #416, run the java process as not Gradle worker but as an isolated process.
To avoid making the build process blocked, we run the process in a worker. From Gradle 6.0, we can inject `ExecOperations` to the  `WorkAction` instance so we can run a process in a worker thread (it was impossible because the worker cannot access a  `Project` instance that provides `#javaexec()` method).
This feature needs one consideration: If we launch a process by `ExecOperations#javaexec()`, we cannot touch its stdout and stderr. So in case of failure, it could be difficult to identify the root cause. For now, I found no way to handle it, so I want to release this feature as disabled-by-default. After we confirmed that this feature really solves the issue, I will enable this feature by default.
To …
> feat: run java process from no-isolated workers

- build.gradle
- src/functionalTest/groovy/com/github/spotbugs/snom/AndroidFunctionalTest.groovy
The trove4j dependency has been republished to Maven Central:
https://search.maven.org/artifact/org.jetbrains.trove4j/trove4j/20160824/jar
Fixes #418
> fix: Replace JCenter repository with Maven Central

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java
Stop accessing the `Project` during the execution phase, to provide better support for Gradle's config cache.
close #446
> provide better support for Gradle config cache

- .github/workflows/gradle.yml
- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/GradleJavaToolchainsSupportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForHybrid.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
- src/test/java/com/github/spotbugs/snom/SpotBugsPluginTest.java
This PR introduces the following changes, to release `5.0.0-beta1`:
* #526
* #363
It also drops support for Gradle v5 and v6, to use Gradle's toolchain support (refer to #526).
> First v5 beta release

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
Enable the `useAuxclasspathFile` option by default, to avoid the "command line exceed operating system limits" problem on the Windows platform. Refs #243
> Set the useAuxclasspathFile option by default

- gradle/publish.gradle
Including SCM information in POM should allow tools like Dependabot figure out the release information. This information is processed correctly for Spotbugs itself, so I just adapted the `scm` block from https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/gradle/publish.gradle
> chore: Include SCM information in POM

- .github/workflows/gradle.yml
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsReport.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
1. Bump up Gradle to the latest release
2. Add a HTML type report
3. Add a `settings.gradle.kts` file as suggested by the [Gradle official user guide](https://docs.gradle.org/7.3.1/userguide/organizing_gradle_projects.html#always_define_a_settings_file).
4. Reproduce and fix the [reported issue](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/629#issuecomment-987013464)
> `required` property cannot disable the report

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
To run the analysis with the Gradle configuration-cache, we need to stop invoking `project.task` at execution phase. To realize it, I applied [lazy `FileCollection` generated via project layout](https://docs.gradle.org/7.3.3/userguide/lazy_configuration.html#working_with_files_in_lazy_properties).
close #662
When I run `CacheabilityFunctionalTest` in my local, I confirmed that the following log was printed in the test report. It proves that a build with `--configuration-cache` option works as expected:
```
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: :spotbugsMain
> Task :compileJava FROM-CACHE
Appending implementation to build cache key: org.gradle.api.tasks.compile.JavaCompile_Decorated@18a7015cb8ac0a07410571947358 …
```
> fix: support Gradle configuration cache

- .github/workflows/codeql.yml
- .github/workflows/gradle.yml
- .github/workflows/javadoc.yml
- README.md
- build.gradle
- gradle/HEADER.txt
- gradle/wrapper/gradle-wrapper.properties
Today the SpotBugs made its latest release v4.7.0:
https://github.com/spotbugs/spotbugs/releases/tag/4.7.0
This PR will bump up the default SpotBugs to this release. Also updates a few things in the build workflow, to keep the codebase secure and updated.
> Bump up the default SpotBugs to v4.7.0

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
Treat the text file generated by our tasks, to keep the task cacheable even when it outputs no report files.
close #630
When we merge this PR, please squash-and-merge because the commit history is little bit noisy.
> fix: SpotBugsTask should be cacheable even when no report is configured by user

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForHybrid.java
Gradle 8 will be dropping some methods from the `ConfigurableReport` class.  By removing the `@Override marker` from some methods and marking getters as `@ReplacedBy`, this will allow a version of SpotBugs to be built which will work with Gradle 7 or 8, and can be smoke tested (internally in the Gradle build) against either version of Gradle.
After Gradle 8.0 is released, a subsequent version of SpotBugs can then fully remove these methods and update its wrapper to use Gradle 8+.
This is an incremental step towards https://github.com/spotbugs/spotbugs-gradle-plugin/issues/600
> Update SpotBugs to work with Gradle 8+

- README.md
- build.gradle
Thanks for merging #782!
When we bump up the dependency on spotbugs-core, it is better to:
1. update the README.md to tell the mapping between versions of gradle-plugin and spotbugs-core,
2. trigger a release by make a commit with `fix:` prefix
Please merge this PR by `squash and merge` and make sure its commit message starts with `fix:` then next release will be made by Gradle automatic.
> fix: bump default spotbugs version from 4.7.1 to 4.7.2

- README.md
- build.gradle
Hey,
there is a new version of spotbugs available (4.7.3) https://github.com/spotbugs/spotbugs/releases/tag/4.7.3 which updates the common-text dependency from 1.9 to 1.10, due it is vulnerable.
This PR just updates the dependency to the latest version.
> fix: bump default spotbugs version from 4.7.2 to 4.7.3

- build.gradle.kts
By #799 I replaced Groovy-based build scripts with Kotlin Script, and it introduced a problem that makes builds on the GitHub Actions failing.
This PR fixes this problem, by using native `System.getenv()` instead of provider-based API. It was my mistake, I should not use provider-based API if I resolve its value during the configuration phase.
> Fix broken builds on the GitHub Actions

- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
> fix: use internal property to avoid issues with configuration cache

- buildSrc/build.gradle.kts
Fixes https://github.com/spotbugs/spotbugs-gradle-plugin/issues/888
> chore: bump com.gradle.plugin-publish to 1.2.0

- src/functionalTest/groovy/com/github/spotbugs/snom/Issue910.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
> Fix Issue 910

- .github/workflows/gradle.yml
- buildSrc/src/main/kotlin/com/github/spotbugs/com.github.spotbugs.test.gradle.kts
- src/functionalTest/groovy/com/github/spotbugs/snom/AndroidFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/GradleJavaToolchainsSupportFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
I merged #925 to fix a known bug, but it introduced a regression.
We could not find this regression because functional test cases were not triggered during the CI workflow. So this PR contains two kinds of fixes:
1. Make `functionalTest` task running during our CI workflow
2. Set path of spotbugs plugins properly
> fix: spotbugs plugin is not loaded from v5.0.15

- src/functionalTest/groovy/com/github/spotbugs/snom/Issue909.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/OutputScanner.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForHybrid.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
Monitor the output from SpotBugs, and make the task failed if it contains related warning.
close #909
> fix: Task does not fail if report generation fails

- .github/workflows/gradle.yml
- package.json
refs https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches
> ci: configure semantic release on the v6 branch

- src/main/groovy/com/github/spotbugs/snom/SpotBugsReport.java
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- Closes #895.
- Closes #819.
- Closes #616.
> fix: migrate deprecated Gradle API usages

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/KotlinBuildScriptFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
Be very explicit on tests compatibility.  Sure tool chains can be used but it hides direct fact these are not compatible.  So lets be very clear on these.
> [tests] Add spock ignoreIf not java 11 to tests that fail on newer jdks

- build.gradle.kts
In the current state, it is essential for the project to be built and tested with JDK 11.
Otherwise either errorprone wouldn't work or tests would fail. This constraint is currently undocumented.
With this commit, we use [Gradle JVM Toolchains](https://docs.gradle.org/current/userguide/toolchains.html)
to pin the JDK that is used to test/build the project to JDK 11. If JDK 11 is already used, nothing happens.
Otherwise, a JDK 11 is downloaded and installed on the users machine.
> build: use JVM Toolchains to pin the JDK version

- .editorconfig
- build.gradle.kts
- buildSrc/src/main/kotlin/com/github/spotbugs/com.github.spotbugs.gradle-plugin.gradle.kts
- gradle.properties
- settings.gradle.kts
- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/KotlinBuildScriptFunctionalTest.groovy
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsExtension.kt
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsReport.kt
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/OutputScanner.kt
> misc: minor things

- src/functionalTest/groovy/com/github/spotbugs/snom/BaseFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/KotlinBuildScriptFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- `--debug` is a little annoying, replace it with `--info`.
- Enable '--warning-mode=fail' to check warnings in tests.
- Bump GE plugin in tests due to some warnings.
- Reuse testKitDir, to share test dependencies cache for speeding up clean build.
> test: tweak common test flags

- .github/workflows/gradle.yml
- README.md
- renovate.json
Our commit hook　is not enough to make commits following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), so introduce `webiny/action-conventional-commits` to verify during the workflow.
This PR also adds a commit with `fix:` prefix, so it will trigger a release for v6.0.4.
> fix: Gradle plugin should require JVM 8 but require JVM 11

- README.md
Documentation doesn't display property.
> docs: Update README.md - fix typo

- .github/workflows/gradle.yml
#1081 failed due to a conflict of uploaded artifacts, which was introduced by #1006.
This PR will resolve this issue by adding an OS identifier to the name of uploaded artifacts.
> ci: avoid conflict of uploaded artifacts

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt
close #1077
I could not find the difference between the previous Groovy implementation and the current Kotlin implementation. However, it is easy to fix the reported issue; just register the report file as output of the `SpotBugsTask`.
> handle reports as output of SpotBugsTask

- .github/workflows/gradle.yml
note: The windows update done on github no longer has PATH set.  Thus the failure.  I don't see much value in javap here.  I think gradle should be ensuring its setup correctly not some post action to confirm.  As such, rather than trying to fix the path (note it runs on macos ok with path), just make it run on linux only for that step as good enough.
> Additionally run on macos and only run javap on linux as not really needed

- build.gradle.kts
We should mark all internal APIs `internal` and let BCV check visibilities.
This reverts the change in https://github.com/spotbugs/spotbugs-gradle-plugin/pull/1064#discussion_r1418501984.
> build: don't ignore API checking for internal package

- README.md
Updated some links in the README.md file that pointed to a netlify instance to point to github pages instead. 
I wanted to access the information in [one of these links](https://spotbugs-gradle-plugin.netlify.com/com/github/spotbugs/snom/spotbugstask) but I noticed the Netlify instance is down. After a bit of searching I noticed there is a github pages with the same information so I replaced the links with the new ones to prevent others from getting the same error I got. 
The links are slightly different, I did my best to match the correct information, but let me know if something seems incorrect
> docs: update links to netlify in readme to use github pages instead

- api/spotbugs-gradle-plugin.api
- src/functionalTest/groovy/com/github/spotbugs/snom/BaseFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.kt
> fix: remaining configuration cache issues

- api/spotbugs-gradle-plugin.api
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsBasePlugin.kt
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsExtension.kt
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsPlugin.kt
The new runOnCheck extension property (defaults to true) can be set to false, which disables the dependency from the `check` task to the spotbugs tasks. This is useful in cases where consumers do not want it to run automatically as part of `gradle check` but will run it in a separate context.
Fixes #1303
> feat: Add an extension property to decouple tasks from check

- src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt
This fixes a bug where local project spotbugs plugins aren't being built when running `spotbugsMain`. Here's our project structure:
```kotlin
// module/build.gradle.kts
plugins {
... java, kotlin, etc...
id("com.github.spotbugs") version "6.1.1"
}
dependencies {
... etc...
spotbugsPlugin(project(":my-spotbugs-plugin))
}
```
```kotlin
// my-spotbugs-plugin/build.gradle.kts
plugins {
... java, kotlin, etc...
}
dependencies {
implementation("com.github.spotbugs:spotbugs:4.9.0")
implementation("com.github.spotbugs:spotbugs-annotations:4.9.0")
}
```
And then when I run `./gradlew module:spotbugsMain`, the task _succeeds_, despite violating the rule defined in `my-spotbugs-plugin`. If, however, I add this, then the task fails as expected:
```kotlin
// module/build.gradle.kts …
```
> fix: pluginJarFiles.from() can accept a Configuration directly.

- .github/workflows/codeql.yml
- .github/workflows/dokka.yml
- .github/workflows/gradle.yml
setup gradle has its own cache, no need for this.
> core(build): Remove gradle cache as not allowed when setup gradle used

- README.md
- api/spotbugs-gradle-plugin.api
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/KotlinBuildScriptFunctionalTest.groovy
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsExtension.kt
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunner.kt
This SpotBugs gradle plugin currently does not support SpotBugs' `chooseVisitors` parameter, which provides the possibility to enable and disable detectors. Without this it's not possible to run detectors disabled by default together with all enabled detectors without specifying all detectors. This PR resolves this problem.
The `chooseVisitors` parameter in the [SpotBugs official documentation](https://spotbugs.readthedocs.io/en/latest/running.html#detector-visitor-configuration-options).
Closes #690 
Pls lmk if I missed anything.
> feat: add support for SpotBugs' chooseVisitors parameter
