spotbugs/spotbugs-gradle-plugin

- .gitignore
- src/main/java/com/github/spotbugs/SpotBugsExtension.java
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
- src/main/java/com/github/spotbugs/SpotBugsTask.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java
Reduce code smells which reported at [Sonarcloud](https://sonarcloud.io/component_measures?id=com.github.spotbugs.gradle&metric=code_smells)
> Reduce code smell

- .travis.yml
- CHANGELOG.md
- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
See #22 for detailed discussion. The changes in this PR comes from @chali's contribution at #24.
> Reproduce #22, and fix it by adding an implementation for abstract method newly added from Gradle v4.8

- .travis.yml
- CHANGELOG.md
- build.gradle
@spotbugs/everyone Please review this PR to support Gradle 4.10. Thanks a lot!
> Release 1.6.3

- CHANGELOG.md
- build.gradle
This should fix #11, but I never heard back from the OP.
Also, I think it would be good to release this version atomically before the existing PRs (#36, #59) get merged; that way if the community reports a problem we can easily revert.
> Release v1.6.5

- CHANGELOG.md
- README.md
- RELEASE_PROCEDURE.md
- build.gradle
This patch update fixes NPE bug introduced at in 1.6.5.
> Release 1.6.6

- CHANGELOG.md
- build.gradle
This PR will release the next patch version 1.6.7.
> Release 1.6.7

- .travis.yml
This change reverts a part of 9f7fa65211fcf7998d2136b4b35e65c3d580ae92 to fix #82.
> Add "on" to run deployment job on tagged commit

- CHANGELOG.md
- build.gradle
After this PR is merged, we'll release 1.6.10 that fixes several known issues.
@spotbugs/everyone please review this PR to merge. Thanks in advance!
> Release 1.6.10

- build.gradle
- gradle/spotless.gradle
- src/main/java/com/github/spotbugs/SpotBugsTask.java
- src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java
- src/test/java/com/github/spotbugs/Issue31Test.java
By this PR, we verify code automatically in CI. For instance, [this build](https://travis-ci.org/spotbugs/spotbugs-gradle-plugin/builds/494690094) was failed because it has wrongly formatted code. Then reviewer can focus not on code format but on important things.
Spotless also provides automatic fix, we can run `./gradlew spotlessApply` then it will fix all problems in the project.
> Verify and fix code format automatically by Spotless

- src/main/java/com/github/spotbugs/SpotBugsPlugin.java
This PR will fix build failure in master branch.
> remove needless "import"

- CHANGELOG.md
- build.gradle
This is minor update that removes needless dead code. It also bumps up version of dependencies.
* https://github.com/spotbugs/spotbugs-gradle-plugin/milestone/4?closed=1
> Release 1.6.11

- CHANGELOG.md
- build.gradle
This version adds three features: #107 and #111. Next version will be [2.0.0](https://github.com/spotbugs/spotbugs-gradle-plugin/milestone/3).
> Release 1.7.0

- CHANGELOG.md
- build.gradle
- src/main/java/com/github/spotbugs/SpotBugsTask.java
Confirmed that this change remove warnings in the build result.
> Release 1.7.1 to fix #131

- .travis.yml
This PR is made from the branch in the same repo. It should run the SonarQube analysis.
> use TRAVIS_SECURE_ENV_VARS instead to judge condition to run Sonar

- CHANGELOG.md
- build.gradle
This release improves performance in big multimodule project, see #167 for detail.
> Release 2.0.1

- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
> Stop verbose output by reusing worker process

- .idea/misc.xml
- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java
These change won't affect feature of this plugin.
> Resolve technical debt pointed by SonarQube

- README.md
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
> Explain how to use Property interface to get actual version

- README.md
I discovered a couple of things while working on a different pull request for this project that I thought would help the next developer, so I added it to the README in a new section on development.
> added documentation to help other developers on this project

- README.md
- build.gradle
- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsSarifReport.java
Support the SARIF format feature which is introduced from SpotBugs 4.1.
> Support SARIF format

- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
This is a minor change to bump up Gradle to the latest version.
> Upgrade Gradle to 6.6.1

- README.md
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
- src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java
This adds support for baseline files for ignoring bugs.
Fixes #348
> Support for baseline files

- .github/workflows/gradle.yml
- build.gradle
This PR will fix the broken build script, to support not only Java 11+ but also Java 8.
close #434
> fix: support for Java 8 was dropped unexpectedly

- .github/workflows/codeql.yml
- .github/workflows/gradle.yml
- gradle/functional-test.gradle
- gradle/test.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/functionalTest/groovy/com/github/spotbugs/snom/AndroidFunctionalTest.groovy
Same to #419 but uses Gradle 7.0.2 instead of its milestone release.
close #480
> Bump up Gradle to 7.0.2

- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsSarifReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTextReport.java
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsXmlReport.java
- src/test/java/com/github/spotbugs/snom/internal/SpotBugsTaskFactoryTest.java
> Replace deprecated Gradle APIs

- README.md
- build.gradle
- package-lock.json
> Update SpotBugs to 4.5.1

- .github/workflows/gradle.yml
- buildSrc/src/main/kotlin/com/github/spotbugs/com.github.spotbugs.test.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
This PR tests the plugin with Gradle v8.0, to ensure that its latest release surely supports Gradle v8.0.
> Bump up Gradle to v8

- src/main/kotlin/com/github/spotbugs/snom/SpotBugsBasePlugin.kt
- src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunner.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunnerForHybrid.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.kt
- src/test/java/com/github/spotbugs/snom/SpotBugsPluginTest.java
> Drop support for old gradle, deprecated APIs, etc.

- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.java
> fix: SpotBugsTask is not configuration cache safe if a stylesheet is set as String for the HTML report

- src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java
Gradle has powerful [configuration avoidance API](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html).
This is already used to great extent in this project. But configurations were still created eagerly.
This PR fixes that.
> feat: create Configurations lazily

- .github/workflows/gradle.yml
- buildSrc/src/main/kotlin/com/github/spotbugs/com.github.spotbugs.test.gradle.kts
- src/functionalTest/groovy/com/github/spotbugs/snom/AndroidFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/BaseFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/BasePluginFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/CacheabilityFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ExtensionFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/GradleJavaToolchainsSupportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/Issue196.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/Issue909.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/Issue910.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/KotlinBuildScriptFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy
- src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy
Reuse common configurations for Gradle runner.
> chore: polish functional tests

- settings.gradle.kts
to trigger a release for #1035
> fix: reported file paths should be split by comma and space

- .github/workflows/gradle.yml
- buildSrc/src/main/kotlin/com/github/spotbugs/com.github.spotbugs.test.gradle.kts
- src/functionalTest/groovy/com/github/spotbugs/snom/BaseFunctionalTest.groovy
See https://github.com/spotbugs/spotbugs-gradle-plugin/pull/989#discussion_r1360009102.
> test: use Gradle property as test Gradle version param

- build.gradle.kts
> misc: mark Dokka tasks CC incompatible

- .github/workflows/gradle.yml
- build.gradle.kts
Fixes #1068. Resubmitting since the checks should all pass now.
> Target JDK8

- settings.gradle.kts
https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration
> chore: migrate to develocity plugin

- build.gradle.kts
- settings.gradle.kts
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.kt
- src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.kt
https://developer.android.com/jetpack/androidx/releases/lint
> chore: add AndroidX Gradle plugin lints and fix errors
